# Generated by Django 2.0.4 on 2019-02-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='nivel',
            field=models.IntegerField(),
        ),
    ]
