# Generated by Django 2.0.4 on 2019-02-21 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
        ('vagas', '0002_auto_20190221_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.Pessoa')),
                ('id_vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.Vaga')),
            ],
        ),
    ]
