# Generated by Django 2.0.4 on 2019-02-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatura',
            name='score',
            field=models.IntegerField(default=-1),
        ),
    ]
